[package]
name = "honnete"
version = "0.0.3"
edition = "2021"

[dependencies]
futures = "0.3"
regex = "1.10.6"
yaml-rust = "0.4.5"
num_cpus = "1.16.0"
clap = { version = "4.5.11", features = ["derive"] }
