---
# Port on which to listen for incoming requests
listening-port: 9700

# Destination hosts to connect to, in hostname:port format
hosts:
  - 127.0.0.1:8000
  - 127.0.0.1:8088
  - 127.0.0.1:8090
  - 127.0.0.1:8092
  - 127.0.0.1:8094
  - 127.0.0.1:8096
  - 127.0.0.1:8100

# number of CPUs to utilize (optional, honnete will default to 4 CPUs if this is not provided)
cpu: 8

# Env level for logging. Choice of test/stage/prod.
env: test
...